version: "3"

services:
  # iotcarsrv:
  #   hostname: iotcarsrv
  #   image: iotagent4fiware/opcuacarsrv:latest
  #   volumes:
  #     - ./CARCONF/car_config.json:/opt/opc-ua-car-server/Car/Car1/config/car_config.json
  #   networks:
  #     - hostnet
  #   ports:
  #     - "5001:5001"

  iotage:
    hostname: iotage
    image: iotagent4fiware/iotagent-opcua:latest
    networks:
      - hostnet
      - iotnet
    ports:
      - "4001:4001"
      - "4081:8080"
    depends_on:
      - iotmongo
      - orion
    volumes:
      - ./config:/usr/src/app/conf
      - ./certificates:/opt/iotagent-opcua/certificates
    environment:
      - IOTA_REGISTRY_TYPE=mongodb #Whether to hold IoT device info in memory or in a database
      - IOTA_LOG_LEVEL=DEBUG # The log level of the IoT Agent
      - IOTA_MONGO_HOST=iot_mongo # The host name of MongoDB
      - IOTA_MONGO_DB=iotagent_opcua # The name of the database used in mongoDB
      #comment if you mind using NGSI-ld
      - IOTA_CB_NGSI_VERSION=v2
      # - IOTA_JSON_LD_CONTEXT=https://uri.etsi.org/ngsi-ld/v1/ngsi-ld-core-context-v1.3.jsonld #comment if you mind using NGSIv2
      # - IOTA_FALLBACK_TENANT=opcua_car
      # - IOTA_RELAX_TEMPLATE_VALIDATION=true

  iotmongo:
    hostname: iot_mongo
    image: mongo:4.2
    networks:
      - iotnet
    volumes:
      - iot_mongo_data:/data/db
      - iot_mongo_conf:/data/configdb

  ################ OCB ################

  orion:
    hostname: orion
    #replace fiware/orion:latest with fiware/orion-ld:0.7.0 if you mind using NGSI-ld
    image: fiware/orion:latest
    #image: fiware/orion-ld:0.7.0
    networks:
      - hostnet
      - ocbnet
    ports:
      - "1026:1026"
    depends_on:
      - orion_mongo
    # add -forwarding if using NGSI-ld
    #command: -statCounters -dbhost orion_mongo -logLevel INFO -forwarding
    command: -statCounters -dbhost orion_mongo -logLevel INFO

  orion_mongo:
    hostname: orion_mongo
    image: mongo:4.2
    networks:
      - ocbnet
    ports:
      - "27017:27017"
    volumes:
      - orion_mongo_data:/data/db
      - orion_mongo_conf:/data/configdb
    command: --nojournal
    
  crate-db:
    image: crate:4.1.4
    hostname: crate-db
    command: crate -Cauth.host_based.enabled=false -Ccluster.name=rampcluster -Chttp.cors.enabled=false -Chttp.cors.allow-origin="*"
    environment:
        - CRATE_HEAP_SIZE=2g
    ports:
        # Admin UI
        - "4200:4200"
        # Transport protocol
        - "4300:4300"
        - "5432:5432"
    volumes:
        - /opt/rampiot/cratedata:/data
    networks: 
        - default
    restart: always

  quantumleap:
    hostname: quantumleap
    image: smartsdk/quantumleap:latest
    depends_on:
        - crate-db
    container_name: fiware-quantumleap
    ports:
        - "8668:8668"
    environment:
        - CRATE_HOST=crate-db
        - CRATE_PORT=4200
        - USE_GEOCODING=True
    networks:
        - default

volumes:
  iot_mongo_data:
  iot_mongo_conf:
  orion_mongo_data:
  orion_mongo_conf:

networks:
  hostnet:
  iotnet:
  ocbnet:
